table Auxiliar
	lineageTag: c7a6e252-d986-4110-832e-f8bfb4b3f235

	column PeriodoNum
		dataType: string
		lineageTag: 6d0dd059-dbf3-41e8-affa-4dea3082f4bd
		summarizeBy: none
		sourceColumn: PeriodoNum

		annotation SummarizationSetBy = Automatic

	column Periodo
		dataType: string
		lineageTag: 2fad6ec3-cff8-4978-8b16-b6da8a65f797
		summarizeBy: none
		sourceColumn: Periodo

		annotation SummarizationSetBy = Automatic

	column Año
		dataType: string
		lineageTag: d3200421-4ce8-429e-9c6e-a896e4c62e5d
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column MesNro
		dataType: int64
		formatString: 0
		lineageTag: d16d0d19-cb6c-44f4-a366-5efe400d04ee
		summarizeBy: sum
		sourceColumn: MesNro

		annotation SummarizationSetBy = Automatic

	column Indicador
		dataType: int64
		formatString: 0
		lineageTag: edc46844-3b07-4abc-acb3-cc169f1ab696
		summarizeBy: sum
		sourceColumn: Indicador

		annotation SummarizationSetBy = Automatic

	partition Auxiliar = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMgABIyUdJd98XzhpaAwkjJRidaDyIK4qRBZEGZqgSoO4kfmRcNLQFFXeFKodKAvWboYqDeJGhrjASUNzVHlzmPYQF7B2C4h0LAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [PeriodoNum = _t, Periodo = _t, Año = _t, MesNro = _t, Indicador = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"PeriodoNum", type text}, {"Periodo", type text}, {"Año", type text}, {"MesNro", Int64.Type}, {"Indicador", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

